name: Deploy to Google App Engine

on:
    workflow_run:
        workflows: ['Node.js CI']
        types:
          - completed
        branches:
            - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'  # Adjust the Node.js version as needed

    - name: Check build status
      run: |
          echo "Build status: ${{ github.event.workflow_run.conclusion }}"
          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
          echo "Previous workflow did not succeed, skipping deploy."
          exit 1
          fi

    - name: Set up Google Cloud SDK
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > /tmp/gcp-key.json
        # Validate JSON format
        if ! jq . /tmp/gcp-key.json > /dev/null; then
          echo "Invalid JSON format in the service account key."
          exit 1
        fi
        gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
        gcloud config set project vertigox  # Replace with your project ID

    - name: Deploy to Google App Engine
      run: |
        gcloud app deploy app.yaml --quiet
